@startuml prodiver-class-diagramm
    package Domain {
        class Player
    }

    interface IEventProvider {
        UnityEvent DefineCollisionHandler(Collision collision);
    }

    interface ICollisionProvider<T> {
        void Handle(Player player, T item);
    }

    class CollisionProvider {
        - ICollisionProvider collisionProvider;
        - Player player;
    }

    class PickableProvider 
    class HitableProvider
    class BonusProvider

    Player --o CollisionProvider
    CollisionProvider --|> IEventProvider
    PickableProvider --|> ICollisionProvider
    HitableProvider --|> ICollisionProvider
    BonusProvider --|> ICollisionProvider
@enduml